#ifndef _IDC_H_
# define _IDC_H_

# define MP3_MUSIC_DIALOG_BOX_IDC 100
# define MP3_ADD_MUSIC_BTN_IDC 101
# define MP3_PLAY_BTN_IDC 102
# define MP3_STOP_BTN_IDC 103
# define MP3_NEXT_BTN_IDC 104
# define MP3_VOLUME_BAR_IDC 150
# define MP3_LCHANEL_VOLUME_BAR_IDC 151
# define MP3_RCHANEL_VOLUME_BAR_IDC 152

# define SYS_MENU_EXIT_BTN_IDC 200
# define SYS_MENU_ADD_BTN_IDC MP3_ADD_MUSIC_BTN_IDC
# define SYS_MENU_RESTART_BTN_IDC 202

#endif